/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A persisted about section returned by the API. */
        AboutSectionResponse: {
            body: string;
            heading: string;
            icon?: string | null;
            /** Format: int64 */
            id: number;
            page: string;
            slug: string;
            /** Format: int64 */
            sort_order: number;
        };
        /** @description Generic JSON error envelope returned on 4xx/5xx responses. */
        ApiError: {
            /** @description Human-readable error message. */
            message: string;
        };
        /** @description A source chunk cited in an `AskResponse`. */
        AskCitation: {
            /** @description Source corpus kind: `rust`, `hcl`, `plan`, or `cache`. */
            kind: string;
            /**
             * Format: int64
             * @description Ordinal position of this chunk within the source file.
             */
            ord: number;
            /** @description Relative path within the repository. */
            path: string;
            /** @description Git SHA at the time of indexing. */
            sha: string;
        };
        /** @description Request body for `POST /api/ask`. */
        AskRequest: {
            /** @description Natural-language question about the deploy-baba codebase. */
            query: string;
            /** @description Maximum number of source chunks to retrieve (default 10, max 20). */
            top_k?: number;
        };
        /** @description Response body for `POST /api/ask`. */
        AskResponse: {
            /** @description The model's grounded answer; every claim cites `[source N]`. */
            answer: string;
            /** @description Source chunks used to construct the answer. */
            citations: components["schemas"]["AskCitation"][];
            /**
             * Format: int32
             * @description Input token count.
             */
            input_tokens: number;
            /** @description Anthropic model ID used to generate the answer. */
            model: string;
            /**
             * Format: int32
             * @description Output token count.
             */
            output_tokens: number;
        };
        /**
         * @description Auth status returned by `GET /api/auth/me`.
         *
         *     The SPA calls this on mount to decide whether to show the dashboard gate.
         */
        AuthMe: {
            authenticated: boolean;
            email?: string | null;
        };
        /** @description Proof-of-work challenge issued by `GET /api/contact/challenge`. */
        ChallengeResponse: {
            /**
             * Format: int32
             * @description Number of leading zero bits required in `SHA256(nonce:solution)`.
             */
            difficulty: number;
            /** @description Random hex nonce to embed in the PoW computation. */
            nonce: string;
            /** @description HMAC-SHA256 signature over `nonce:timestamp:difficulty`. */
            signature: string;
            /**
             * Format: int64
             * @description Unix timestamp (seconds) when the challenge was issued.
             */
            timestamp: number;
        };
        /** @description A competency / skill category. */
        Competency: {
            description: string;
            icon?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
            /** Format: int64 */
            sort_order: number;
        };
        /** @description A competency with its supporting evidence items. */
        CompetencyWithEvidence: components["schemas"]["Competency"] & {
            evidence: components["schemas"]["EvidenceItem"][];
        };
        /** @description Response from `POST /api/contact`. */
        ContactResponse: {
            message: string;
            success: boolean;
        };
        /** @description Request body for `POST /api/contact`. */
        ContactSubmitRequest: {
            email: string;
            message: string;
            name: string;
            /** @description Nonce from the challenge response. */
            pow_nonce: string;
            /** @description HMAC signature from the challenge response. */
            pow_signature: string;
            /**
             * Format: int64
             * @description Counter that satisfies the proof-of-work difficulty.
             */
            pow_solution: number;
            /**
             * Format: int64
             * @description Timestamp from the challenge response.
             */
            pow_timestamp: number;
            subject: string;
            /** @description Honeypot — must be empty for legitimate submissions. */
            website?: string;
        };
        /** @description Information about a single deploy-baba library crate. */
        CrateInfo: {
            /** @description Short description of the crate's purpose. */
            description: string;
            /** @description Crate package name (e.g. `"api-openapi"`). */
            name: string;
            /** @description Trait names this crate implements or exposes. */
            traits: string[];
            /** @description Semver version string. */
            version: string;
        };
        /** @description A cross-referenced evidence item linking a competency to a job detail. */
        EvidenceItem: {
            company: string;
            /** Format: int64 */
            detail_id?: number | null;
            detail_text?: string | null;
            highlight_text?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            job_id: number;
            job_slug: string;
            /** Format: int64 */
            sort_order: number;
        };
        /** @description A single typed field definition used in `GenerateSpecRequest`. */
        Field: {
            /** @description Field name. */
            name: string;
            /** @description Whether this field is required in the generated schema. */
            required: boolean;
            /** @description JSON Schema primitive type: `"string"`, `"integer"`, `"boolean"`, etc. */
            type: string;
        };
        /** @description Request body for `POST /api/demo/spec/generate`. */
        GenerateSpecRequest: {
            /** @description Fields that form the resource schema. */
            fields: components["schemas"]["Field"][];
            /** @description Title of the generated OpenAPI spec. */
            title: string;
        };
        /** @description Response from `POST /api/demo/spec/generate`. */
        GenerateSpecResponse: {
            /** @description The generated OpenAPI 3.0 spec as a JSON object. */
            spec: unknown;
        };
        /** @description Service health check response. */
        HealthResponse: {
            /** @description Status string, always `"ok"` when the service is healthy. */
            status: string;
            /** @description Semver version of the deployed binary. */
            version: string;
        };
        /** @description A single job position. */
        Job: {
            company: string;
            end_date?: string | null;
            /** Format: int64 */
            id: number;
            location?: string | null;
            slug: string;
            /** Format: int64 */
            sort_order: number;
            start_date: string;
            summary: string;
            /** @description Technology names, split from comma-separated DB storage. */
            tech_stack?: string[] | null;
            title: string;
        };
        /** @description A bullet-point accomplishment tied to a job. */
        JobDetail: {
            category?: string | null;
            detail_text: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            sort_order: number;
        };
        /** @description A job with its associated bullet-point details. */
        JobWithDetails: components["schemas"]["Job"] & {
            details: components["schemas"]["JobDetail"][];
        };
        /** @description Query parameters for `GET /api/jobs`. */
        JobsQuery: {
            /** @description View mode: `"chronological"` (default). */
            view?: string | null;
        };
        /** @description Request body for `POST /api/demo/config/parse`. */
        ParseConfigRequest: {
            /** @description Raw config text to parse. */
            content: string;
            /** @description Format of the config content: `"toml"`, `"json"`, or `"yaml"`. */
            format: string;
        };
        /** @description Response from `POST /api/demo/config/parse`. */
        ParseConfigResponse: {
            /** @description Human-readable error message, if parsing failed. */
            error?: string | null;
            /** @description Parsed representation as JSON, if successful. */
            parsed?: unknown;
            /** @description Whether parsing succeeded. */
            success: boolean;
        };
        /**
         * @description Combined resume payload returned by `GET /api/resume`.
         *
         *     Bundles bio, jobs, competencies, and social links so the SPA home page
         *     can render the full resume with a single fetch.
         */
        ResumeData: {
            bio: string;
            competencies: components["schemas"]["Competency"][];
            jobs: components["schemas"]["Job"][];
            social_links: components["schemas"]["SocialLink"][];
            summary: string;
        };
        /**
         * @description A social link as used in nav rendering (url + label only).
         *
         *     This is the same shape as `services/ui/src/db.rs::SocialLink`.
         *     `db.rs` re-exports this type via `pub use api_openapi::models::social::SocialLink`.
         */
        SocialLink: {
            label: string;
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
